name: Maven

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21']
        #jdk: ['8', '11', '15', '17']
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
        server-id: github
        # server-username: 'SingingBush'
        # server-password: ${{ secrets.ACCESS_TOKEN  }}

    - name: Build with Maven
      working-directory: microemulator
      run: mvn -B package --file pom.xml -P Github-Jour -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
