name: Maven

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }} ${{ matrix.distribution }}
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21']
        #jdk: ['8', '11', '15', '17']
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        distribution: [ 'temurin' ]
        #include:
        #  - { jdk: '8', distribution: 'oracle' }
        #  - { jdk: '8', distribution: 'adopt' }
        #  - { jdk: '8', distribution: 'liberica' }

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.jdk }} ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
        server-id: github
        server-username: USER_NAME
        server-password: ACCESS_TOKEN
        # server-username: 'SingingBush'
        # server-password: ${{ secrets.ACCESS_TOKEN  }}

    - name: Build with Maven
      working-directory: microemulator
      run: mvn -B package --file pom.xml -P github -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
      env:
        # USER_NAME: ${{ secrets.USER_NAME }}
        USER_NAME: 'SingingBush'
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
